/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedInterviewApplicationIdRouteImport } from './routes/_authenticated/interview.$applicationId'
import { Route as AuthenticatedRecruiterJobsNewRouteImport } from './routes/_authenticated/recruiter.jobs.new'
import { Route as AuthenticatedRecruiterApplicationsAppIdRouteImport } from './routes/_authenticated/recruiter.applications.$appId'
import { Route as AuthenticatedRecruiterJobsJobIdApplicantsRouteImport } from './routes/_authenticated/recruiter.jobs.$jobId.applicants'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewApplicationIdRoute =
  AuthenticatedInterviewApplicationIdRouteImport.update({
    id: '/interview/$applicationId',
    path: '/interview/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsNewRoute =
  AuthenticatedRecruiterJobsNewRouteImport.update({
    id: '/recruiter/jobs/new',
    path: '/recruiter/jobs/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterApplicationsAppIdRoute =
  AuthenticatedRecruiterApplicationsAppIdRouteImport.update({
    id: '/recruiter/applications/$appId',
    path: '/recruiter/applications/$appId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsJobIdApplicantsRoute =
  AuthenticatedRecruiterJobsJobIdApplicantsRouteImport.update({
    id: '/recruiter/jobs/$jobId/applicants',
    path: '/recruiter/jobs/$jobId/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/interview/$applicationId': typeof AuthenticatedInterviewApplicationIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/recruiter/applications/$appId': typeof AuthenticatedRecruiterApplicationsAppIdRoute
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/jobs/$jobId/applicants': typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/interview/$applicationId': typeof AuthenticatedInterviewApplicationIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/recruiter/applications/$appId': typeof AuthenticatedRecruiterApplicationsAppIdRoute
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/recruiter/jobs/$jobId/applicants': typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/interview/$applicationId': typeof AuthenticatedInterviewApplicationIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/recruiter/applications/$appId': typeof AuthenticatedRecruiterApplicationsAppIdRoute
  '/_authenticated/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/_authenticated/recruiter/jobs/$jobId/applicants': typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/api/transcribe'
    | '/interview/$applicationId'
    | '/jobs/$jobId'
    | '/jobs/'
    | '/recruiter/applications/$appId'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs/$jobId/applicants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/api/transcribe'
    | '/interview/$applicationId'
    | '/jobs/$jobId'
    | '/jobs'
    | '/recruiter/applications/$appId'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs/$jobId/applicants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/api/transcribe'
    | '/_authenticated/interview/$applicationId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/'
    | '/_authenticated/recruiter/applications/$appId'
    | '/_authenticated/recruiter/jobs/new'
    | '/_authenticated/recruiter/jobs/$jobId/applicants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$applicationId': {
      id: '/_authenticated/interview/$applicationId'
      path: '/interview/$applicationId'
      fullPath: '/interview/$applicationId'
      preLoaderRoute: typeof AuthenticatedInterviewApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/jobs/new': {
      id: '/_authenticated/recruiter/jobs/new'
      path: '/recruiter/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/applications/$appId': {
      id: '/_authenticated/recruiter/applications/$appId'
      path: '/recruiter/applications/$appId'
      fullPath: '/recruiter/applications/$appId'
      preLoaderRoute: typeof AuthenticatedRecruiterApplicationsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/jobs/$jobId/applicants': {
      id: '/_authenticated/recruiter/jobs/$jobId/applicants'
      path: '/recruiter/jobs/$jobId/applicants'
      fullPath: '/recruiter/jobs/$jobId/applicants'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewApplicationIdRoute: typeof AuthenticatedInterviewApplicationIdRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedRecruiterApplicationsAppIdRoute: typeof AuthenticatedRecruiterApplicationsAppIdRoute
  AuthenticatedRecruiterJobsNewRoute: typeof AuthenticatedRecruiterJobsNewRoute
  AuthenticatedRecruiterJobsJobIdApplicantsRoute: typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewApplicationIdRoute:
    AuthenticatedInterviewApplicationIdRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedRecruiterApplicationsAppIdRoute:
    AuthenticatedRecruiterApplicationsAppIdRoute,
  AuthenticatedRecruiterJobsNewRoute: AuthenticatedRecruiterJobsNewRoute,
  AuthenticatedRecruiterJobsJobIdApplicantsRoute:
    AuthenticatedRecruiterJobsJobIdApplicantsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
